pipeline {
    agent any

    environment {
        NODE_ENV = "development"
        // Environment Variables
        ENV_FILE_CONTENTS = credentials('ENV_FILE_CONTENTS')
        // Docker Hub Credentials
        DOCKERHUB_CRED = 'dockerhub-cred'
        DOCKERHUB_REPO = 'somjeetsrimani/smart-commute-planner'
        IMAGE_TAG = '${env.BUILD_NUMBER}-${env.GIT_COMMIT.substring(0, 7)}'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Prepare Environment') {
            parallel {
                stage('Clean Node Modules & Npm Cache') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                        }
                    }
                    steps {
                        sh 'rm -rf node_modules'
                        sh 'npm cache clean --force'
                    }
                }
                stage('Checkout') {
                    steps {
                        checkout scmGit(branches: [[name: '*/development']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/somjeet2000/smart-commute-planner-server.git']])
                    }
                }
            }
        }

        // stage('Checkout') {
        //     steps {
        //         checkout scmGit(branches: [[name: '*/development']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/somjeet2000/smart-commute-planner-server.git']])
        //     }
        // }

        // stage('Clean Node Modules & Npm Cache') {
        //     agent {
        //         docker {
        //             image 'node:20-alpine' // Use an appropriate Node.js image
        //             args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // Mount Docker socket
        //         }
        //     }
        //     steps {
        //         sh 'rm -rf node_modules'
        //         sh 'npm cache clean --force'
        //     }
        // }

        stage('Install Dependencies') {
            agent {
                docker {
                    image 'node:20-alpine' // Use an appropriate Node.js image
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // Mount Docker socket
                }
            }
            steps {
                // Install Musl libraries explicitly
                sh 'apk add --no-cache musl'
                sh 'apk add --no-cache libc6-compat' // For compatibility with libraries that expect glibc
                sh 'npm install'
            }
        }

        // This step will run for unit test cases available
        stage('Run Tests') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '--user root -v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                sh '''export \$(echo "$ENV_FILE_CONTENTS" | xargs)
                    npm test'''
                junit 'test-results/**/*.xml'
            }
        }

        // Stage - Build docker image works
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKERHUB_REPO:$IMAGE_TAG .'
                }
            }
        }

        // Stage - Push to Docker Hub works
        stage('Push to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: env.DOCKERHUB_CRED, passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                        sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
                        sh 'docker push $DOCKERHUB_REPO:$IMAGE_TAG'
                    }
                }
            }
        }

        // Clean up docker images
        stage('Cleanup Docker Images') {
            steps {
                sh 'docker rmi $DOCKERHUB_REPO:$IMAGE_TAG'
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}